### ISSUE TITLE
Articles don't display on OS 10.4

### ISSUE THREAD

**Issue by sbliven** [wikiwidget/wikipedia-widget#6]
System: iMac 6,1 (2.33 GHz Core 2 Duo, OS X 10.4.11)

User report:
When I enter a search text & press enter, it does nothing. Clicking on the "Wikipedia" button tries to load http://undefined.wikipedia.org/wiki/Special:Search?search=wiki&go=Go, which displays "Safari can't find the server "undefined.wikipedia.org"." Clicking on the "?" or info buttons have no response. (The info button, normally an "i", displays as a grey circle with no text.)

I viewed the Change Log at http://wikiwidget.github.com/ & downloaded versions 0.9.6 & 0.9.5 to try, but they responded the same way as ver 1.0.0.

I downloaded ver 0.9.4, & it appears to run. The "i" button displays correctly & accesses the settings on the back. The "?" button enters a Special:Randompage. Clicking the "Wikipedia" button opens a browser page with the specified search term. But nothing displays in the results area of the widget - the 'activity gear wheel' spins & spins. I have trashed the plist, emptied cache, deleted cookies, & cleared resent searches, but nothing displays in the results field.

**Comment by sbliven** [comment]
Until I can find a 10.4 computer to debug the widget on I'm going to increase the minimum version to 10.5. I haven't tested the widget there, but there were a number of advancements to Dashboard in 10.5 that make it easier to maintain compatibility with. The goal is still to be compatible with all versions of Dashboard, so hopefully I can reduce the minimum requirement in the future.

If anyone can confirm that v1.0.0 runs or doesn't run on 10.5, please respond in a comment.

**Comment by egregea** [comment]
I am running 10.6.8, and v1.0.0 runs but shows the second issue:
After entering a search, the widget does not retrieve results.
Nothing displays in the results area, though the "activity gear wheel" is running.
It does seem to find the wikipedia article -- if I enter "harry potter" the search term changes to "Harry Potter". 

The wheel keeps on spinning until I press the "cancel" button. Then it stops instantly.

**Comment by sbliven** [comment]
In #7, @egregea reported that his/her problems were fixed by uninstalling FuzzyClock. We should double check that the widget consistently doesn't run on 10.4, and that this isn't actually an incompatibility problem.

**Comment by sbliven** [comment]
This issue seems to have been fixed, and anyways 10.4 is long expired.
