### ISSUE TITLE
No response from Wikipedia

### ISSUE THREAD

**Issue by wgeoghegan** [wikiwidget/wikipedia-widget#7]
My Wikipedia widget will not retrieve anything.

**Comment by sbliven** [comment]
Can you provide some more details, please? What version of the widget, and what version of OSX? Make sure you're use the latest version (1.0.0)

**Comment by wgeoghegan** [comment]
Have latest version 1.0.0 and OSX 10.8.2

**Comment by egregea** [comment]
System 10.6.8, widget 1.0.0

Cross posting from other open issue:
After entering a search, the widget does not retrieve results.
Nothing displays in the results area, though the "activity gear wheel" is running.
It does seem to find the wikipedia article -- if I enter "harry potter" the search term changes to "Harry Potter". 

The wheel keeps on spinning until I press the "cancel" button. Then it stops instantly.

**Comment by sbliven** [comment]
@wgeoghegan Strange, the widget works perfectly for me on 10.8.2. Can you try the following?
1. Uninstall the widget
   - Click the '+' in the lower left of your dashboard
   - Click the '-'. All your widgets should start shaking
   - Click the 'x' in the corner of the Wikipedia widget
2. Delete the following files/folders (~/Library can be accessed from Finder by holding Option and clicking on the 'Go' menu.)
   1. ~/Library/Caches/WikipediaWidget
   2. ~/Library/Preferences/widget-com.whatsinthehouse.widget.wikipedia.plist
3. Download a fresh copy from http://wikiwidget.github.com/downloads/Wikipedia.zip
4. Install & verify that the back of the widget reads '1.0.0' in the bottom corner

If that doesn't work, there may be some incompatibility with something else you have installed on your computer.

**Comment by wgeoghegan** [comment]
I haven idea but I changed the color of the widget to red and it stated working.

**Comment by egregea** [comment]
Hi,
I'm on another computer at the moment, and it's got 10.8.2 -- exactly the same problem manifests, even after the solution above. (uninstall and delete widget, remove cache and preferences, reinstall 1.0 of widget)

Even changing it to red didn't help.

Note: this is a different computer, with a different system, and almost entirely different apps installed. The only non-system installs are DropBox and FuzzyClock.  I will be able to try the other computer in an hour or so and will try installing without those two apps.

Any further thoughts? Is there some sort of debugging dump I can send you?

NB: the gear wheel pauses for just a second, the search field is updated with proper capitalization, then from that point, perpetual nothingness.

**Comment by egregea** [comment]
SOLVED. On 10.8.2 and on 10.6.8, the problem was a menubar app called "FuzzyClock". Remove it from "Login Items" and restart - widget works perfectly. Put it back in, widget stops working.

**Comment by wgeoghegan** [comment]
Where is "Login Items" located?

**Comment by egregea** [comment]
It's a control panel, Users and Accounts or similar name... Login Items is a list of the apps to auto- open on startup.

**Comment by sbliven** [comment]
Great to hear, @egregea! I'll add FuzzyClock to the readme as a known incompatible software. Thanks for taking the time to figure it out.

**Comment by wgeoghegan** [comment]
I don't have "FuzzyClock' listed in Login in items.

**Comment by sbliven** [comment]
@wgeoghegan Any other apps that could possibly be interfering? Note that there's nothing special about the Login Items, its just that these apps are restarted every time you reboot.

You aren't doing anything unusual with your network settings, are you? Proxy, VPN, etc?
